name: Convert Markdown to PDF

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  convert-markdown-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Convert all Markdown to PDF
        run: |
          mkdir -p output
          for file in $(find . -name "*.md"); do
            filename=$(basename "$file" .md)
            pandoc "$file" -o "output/$filename.pdf" --pdf-engine=xelatex --toc --metadata link-citations=true
          done

      - name: Upload PDF files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf-files
          path: output/
